#
#
#
name: The EIC Software Group Website
title: The EIC Software Group Website
description: The EIC Software Group Website
url: https://eic.github.io
#
excerpt_separator: <!--more-->
timezone: America/New_York
highlighter: rouge
#
markdown: kramdown
future: true
exclude: [vendor]

##################################################################################
# Important if we are not serving from the top folder - baseurl: /web            #
# In that case, please make sure you use the "relative_path" directive           #
# everywhere you include various site URLs in your pages.                        #
#                                                                                #
# Currently serving from the top folder i.e.                                     #
# in this case this does not apply until further notice.                         #
##################################################################################

# Custom helper variables:
blank: 'target="_blank"'


# Layout
tablepadding: ' '

# Decorative elements
eic_logo: /assets/images/site/EIClogo_small.png
splash: /assets/images/site/ion-collision-xparent-cropped.png

# Icons:
home_icon: /assets/images/site/icons/house-32.png
external_icon: /assets/images/site/icons/external-link-48.png

software_icon: /assets/images/site/icons/console-32.png
computing_icon: /assets/images/site/icons/cog-32.png
people_icon: /assets/images/site/icons/group-32.png
resources_icon: /assets/images/site/icons/literature-32.png
about_icon: /assets/images/site/icons/light-bulb-5-32.png


# Development:
display_news: yes
#
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-redirect-from

#
collections:
  people:
    output: true
    permalink: /people/:title.html
  eic:
    output: true
    permalink: /eic/:title.html
  software:
    output: true
    permalink: /software/:title.html
  computing:
    output: true
    permalink: /computing/:title.html
  teams:
    output: true
    permalink: /teams/:title.html
  about:
    output: true
    permalink: /about/:title.html
